#!/usr/bin/perl
use strict;
use warnings;

use Config::Simple;
use Log::Dispatch::Screen;
use Net::Flickr::Backup;

my $cfg = Config::Simple->new('/home/rjbs/.flickr-backup');

my $flickr = Net::Flickr::Backup->new($cfg);

my $feedback = Log::Dispatch::Screen->new(
  'name'      => 'info',
  'min_level' => 'info'
);

$flickr->log()->add($feedback);
$flickr->backup();

