#!/usr/bin/perl
use Data::GUID;
use Getopt::Long::Descriptive;

my ($opt, $usage) = describe_options(
  '%c %o',
  [ "game-encoded|g", "encode the guid for use in The Game" ],
);

my $guid = Data::GUID->new;

if ($opt->{game_encoded}) {
  require Math::BigInt;
  my $int = Math::BigInt->new($guid->as_hex);
  require Number::Nary;
  my $string = Number::Nary::n_encode(
    $int, 
    join '', (1 .. 9, 'a' .. 'z')
  );

  my $dashes;
  my $since;
  for (my $i = 1; $i < length $string; $i++) {
    if ($since > 6 or rand > 0.8) {
      substr $string, $i, 0, '-';
      $i += 2;
      ($dashes ||= 'A')++;
      $since = 0;
    }
    $since++;
  }
  print "$dashes:$string\n";
} else {
  print $guid->as_string, "\n";
}
