#!/usr/bin/perl
use strict;
use warnings;

use Email::Folder;
use Email::Date;
use List::Util qw(sum);
use Time::Duration;

my $folder = Email::Folder->new($ENV{HOME} . "/Maildir/INBOX/");

my $maxdur = 0;
my @ages;
for my $message ($folder->messages) {
  my $date = find_date($message);
  my $age = $^T - $date->epoch;
  $maxdur = $age if $age > $maxdur;
  push @ages, $age;
}

my $avg = sum(@ages) / @ages;

print "oldest : ", duration($maxdur), "\n";
print "average: ", duration($avg), "\n";
