#!/usr/bin/perl
use warnings;
use strict;

use File::Copy qw(move);

my $regex = pop @ARGV;
my @files = @ARGV;

die "usage: mvre [ files ] 's/foo/bar/'\n" unless $regex and @files;

my $substitute_sub = sub {
  my $filename = shift;
  my $new_file = eval qq{
    (my \$new_file = \$filename) =~ $regex;
    \$new_file;
  };
  die $@ if $@;
};

for my $filename (@files) {
  warn "mvre: no such file: $filename\n" unless -f $filename;
  my $new_file = $substitute_sub->($filename);
  unless ($new_file) { warn "couldn't munge filename $filename\n"; next; }
  print "renaming $filename to $new_file\n";
  move $filename => $new_file or warn "couldn't move file $filename";
}
