#!/usr/bin/perl

use strict;

my %priorities = (
	1 => 'high',
	5 => 'medium',
	9 => 'low',
	0 => 'undefined',
);

use Mac::Glue;
my $ical = new Mac::Glue("iCal");

my @todos;

my @cals = $ical->prop("calendars")->get;
foreach my $cal (@cals) {
	my $name = $cal->prop("title")->get;
	foreach my $todo ($cal->prop("todos")->get) {
		next if $todo->prop("completion_date")->get;
		push @todos, {
			cal		=> $name,
			brief	=> $todo->prop("summary")->get,
			priority=> $priorities{ $todo->prop("priority")->get }
		};
	}
}

#use YAML;
#print Dump(\@todos);

use Template;

my $template = Template->new;
   $template->process("ical.tt", { todos => \@todos }) || die $template->error;
