#!/usr/bin/perl

$dictionaryfile = "eo_dict.txt";

print "Vortaro: ";
LOOKUP: while ($input=<STDIN>) {
  chomp($input);
  last LOOKUP if $input =~ /^$/;
  lu_esp($input);
  print "Vortaro: ";
}

sub lu_esp($input) {

  open(DICT,$dictionaryfile);
  $done=0; $hit=0; $i=0;
  undef @entry; undef @word;

  while (($done==0) and ($inline=<DICT>)) {
    if ($inline =~ /^($input)\t(.*)\n/) {
      $hit=1; $word[$i]=$1; $entry[$i++]=$2;
    } elsif ($hit==1) {
      $done=1;
    }
  }
  if (@entry > 0) {
    for ($i=0; $i<@entry; $i++) {
      print "Angla por $word[$i]: ";
      @meanings = split("\t",$entry[$i]);
      if (@meanings > 1) { 
        print "\n";
        for ($j=0; $j<@meanings; $j++) {
          printf " (%2u) $meanings[$j]\n",$j+1;
        }
      } else {
        print "$entry[$i]\n";
      }
    }
  } else { print "Neniom parigojn trovis je $input.\n"; }
  close(DICT);
}
