#!/usr/bin/perl
use strict;
use warnings;

use CPAN::Mini::Archive;

my $remote = CPAN::Mini::Archive->new(
  root => 'file:///Users/rjbs/code/perl/minicpan2/fpan/'
);

my $local  = CPAN::Mini::Archive->new(
  root => 'file:///Users/rjbs/code/perl/minicpan2/fpan_old/'
);

CPAN::Mini::Mirror->mirror($remote, $local);
