#!/usr/bin/perl
use strict;
use warnings;

use CPAN::Mini::Archive;
use CPAN::Mini::Archive::WriteIndex;

use Cwd;

my $archive =
	# CPAN::Mini::Archive->new(root => "http://cpan.mirrors.manxome.org/");
	CPAN::Mini::Archive->new(root => "file://" . cwd . "/cpan/");

print CPAN::Mini::Archive::WriteIndex->__02packages_content($archive);
print CPAN::Mini::Archive::WriteIndex->__01mailrc_content($archive);

CPAN::Mini::Archive::WriteIndex->write($archive, '.');

