#!/usr/bin/perl

## by rjbs
## origin: unknown; when working on Esperanto scrabble
## counts characters in Esperanto text, consolodating digraphs into one

open(INFILE,$ARGV[0]);

while ($inline=lc(<INFILE>)) {
  $i=0; $cc="";
  while ($cc ne "\n") {
    $cc=substr($inline,$i++,1);
    if (($cc eq "c") or ($cc eq "g") or  ($cc eq "j") or 
        ($cc eq "s") or ($cc eq "h") or ($cc eq "u")) {
      if (substr($inline,$i,1) eq "x") { 
        $occ{$cc . "x"}++; $i++;
      } else { 
        $occ{$cc}++;
      }
    } else {
      $occ{$cc}++;
    }
  }
}

close(INFILE);
foreach $key (sort(keys(%occ))) {
  if ($key ne "\n") { printf "%2s : $occ{$key}\n", $key; }
}
