#!/usr/bin/perl

## by rjbs
## origin: when converting epic logfiles to irssi naming format
## splits an epic logfile into many files when day or time changes

open(IPF,"<$ARGV[0]");

%m = (
	Jan => '01',
	Feb => '02',
	Mar => '03',
	Apr => '04',
	May => '05',
	Jun => '06',
	Jul => '07',
	Aug => '08',
	Sep => '09',
	Oct => '10',
	Nov => '11',
	Dec => '12',
);

goto LOOP;
LABEL:
open(OPF,">$ARGV[0]-$time");
print OPF $line;
LOOP:
while ($line=<IPF>) {
	if (($line =~ /^----- .+([A-Z][a-z][a-z]) +(\d{1,2}) (\d\d:\d\d:\d\d) (\d{4}) -----/) and ($line !~ /ended/)) {
		$time = sprintf "$4-$m{$1}-%02uT$3", $2; close(OPF); goto LABEL;
	} else { print OPF $line; }
}
unlink("$ARGV[0].1");
