#!/usr/bin/perl

=head1 NAME 

iclfile - file iChat logs under the right archive directory

=cut

use strict;
use warnings;

use File::Copy;

my $from = "/Users/rjbs/Documents/iChats/";
my $to   = "/Users/rjbs/log/ichat/";

for (<$from*.ichat>) {
	next unless my ($name, $date, $etc) =
		m!\A$from(.+) on (\d{4}-\d\d-\d\d) at (.+).chat\Z!;
	$etc =~ tr/# :/-/d;
	($name = lc $name) =~ tr/ ./_/d;
	
	mkdir "$to/$name" unless -d "$to/$name";
	move $_ => "$to/$name/${date}T$etc.chat"
		or die "Move failed: $!";
	print "moved $_\n";
}
