#!/usr/bin/perl

use File::Find;

$dir = $ARGV[0] || 'Maildir';
@foo = <~/$dir/.*/new>;

find(\&wanted,@foo);

sub wanted {
	my $dir = "/INBOX";
	if ($File::Find::dir =~ /\.([^\/]+)\/new$/) {
		$dir .= "/$1";
		$dir =~ s/\./\//g;
	}
	$new{$dir}++ unless ($_ eq '.');
}

foreach $key (sort keys %new) {
	printf "%-30s: %3u\n", $key, $new{$key};
	$total += $new{$key};
}

if ($total) {
	printf "%30s: %3u\n", 'total', $total;
} else {
	print "lm: no new messages\n";
}
