#!/bin/perl
use strict; use warnings;

my ($playlist, @songs, %played);
die "usage: mprand [playlist.txt]" unless $playlist = shift;

$SIG{HUP} = \&start_up;

sub start_up { (@songs, %played) = (); get_songs(); 1; }
sub get_songs { open my $pl, '<', $playlist; @songs = <$pl>; chomp for @songs; }

sub play_songs {
	while (1) {
		my $next = int((@songs+1) * rand());
		next if $played{$next};
		die "ogg123 exited with non-zero result"
			if (system('ogg123', $songs[$next]));
		$played{$next} = 1;
		%played = () if (keys %played == @songs);
	}
}

start_up and play_songs;
