#!/usr/bin/perl

## by rjbs
## origin: creation of the reference
## creates an html index for a directory full of man pages

$files=`echo man$ARGV[0]/*.$ARGV[0].html`;
@files=split(" ",$files);

open(OUTFILE,">/home/samael/section$ARGV[0].html");                     

print OUTFILE "<html>\n<head>\n";
print OUTFILE "<title>Manual Pages: Section $ARGV[0]</title>\n</head>\n";
print OUTFILE "<h1>Manual Pages: Section $ARGV[0]</h2><p />\n";
print OUTFILE "<table width=\"100%\">\n";

for($i=0; $i<@files; $i++) {
  $files[$i] =~ /man$ARGV[0]\/(.+)\.$ARGV[0]\.html/;
  if (($i % 3) == 0) {
    print OUTFILE "<tr><td><a href=\"$files[$i]\">$1</a></td>\n";
  } elsif (($i % 3) == 1) {
    print OUTFILE "  <td><a href=\"$files[$i]\">$1</a></td>\n";
  } elsif (($i % 3) == 2) {
    print OUTFILE "  <td><a href=\"$files[$i]\">$1</a></td>\n</tr>\n";
  }
}

print OUTFILE "</body>\n</body>\n</html>\n";

close(OUTFILE);

