#!/usr/local/bin/perl

# MCM: Mail Checking Module v2.0.1
# (c) 2000 by Ricardo Signes

# lists new messages in mail folders in mbox format

$version = "2.0";
$mailbox = "/home/samael/Mailbox";
$mailloc = "/home/samael/mail/";

sub count_new {
	open(IPF,$_[0]);
	$count=0; $read=0;
	while ($line=<IPF>) {
		chomp($line);
		if ($line =~ /^From ([\S]+) {0,3}[MTWFS][a-z]{2} [A-Z][a-z]{2} .+/) {
			$count++;
		} elsif ($line =~ /^Status: [A-Z]*R[A-Z]*$/) {
			$read++;
		}
	}
	return($count-$read);
	close(IPF);
}

sub list_mails {
	open(IPF,$_[0]);
	while ($line=<IPF>) {
		chomp($line);
		if ($line =~ /^From: ([\w\s\@\.]+)|( <[\w\.\@]+>)/) {
			$from=$1; 
			printf("%10.10s",$from);
		}
	}
	close(IPF);
}	

if (($ARGV[0] eq "") | ($ARGV[0] eq "-i")) {
	opendir(MAILDIR,$mailloc);
	$cn=count_new($mailbox);
	print "inbox: $cn new messages\n";
} elsif ($ARGV[0] eq "-a") {
	$cn=count_new($mailbox);
	print "inbox: $cn new messages\n";
	opendir(MAILDIR,$mailloc);
	@folders=sort(grep(!/^\./,readdir(MAILDIR)));
	foreach $folder (@folders) {
		$cn=count_new($mailloc . $folder);
		if ($cn>0) {
			print "$folder: $cn new messages\n";
		}
	}
} elsif ($ARGV[0] eq "-f") {
	list_mails($mailbox);	
} else {
	print "mcm  : Mail Checking Module v$version\n";
	print "usage: mcm [option]\n";
	print "       -i : check inbox (default)\n";
	print "       -a : check all folders\n";
}	
