#!/usr/bin/perl

## by rjbs
## origin: when learning perl
## emilates output of free(1)

open(MEMINFO,"/proc/meminfo");
<MEMINFO>;
$read=<MEMINFO>;
#print "$read\n";
@stat=split(" ",$read);
$memtotal=$stat[1];  $memused =$stat[2];  $memfree =$stat[3];
$memshare=$stat[4];  $membuff =$stat[5];  $memcache=$stat[6];

$read=<MEMINFO>;
@stat=split(" ",$read);
$swaptotal=$stat[1]; $swapused =$stat[2]; $swapfree =$stat[3];

print "             total       used       free     shared    buffers     cached\n";
printf "Mem: %13u %10u %10u %10u %10u %10u\n", $memtotal/1024, $memused/1024, $memfree/1024, $memshare/1024, $membuff/1024, $memcache/1024;
$read=$memused-$membuff-$memcache;
printf "+/- buffers: %16u %10u\n",$read/1024,($memtotal-$read)/1024;
printf "Swap: %12u %10u %10u\n",$swaptotal, $swapused, $swapfree;

close(MEMINFO);
